### PR TITLE
Use Level.INFO insted of Level.FINE and fix an typo (i guess?)

### PR DESCRIPTION
**Pull request by ElectroBoy404NotFound**

### CODE REVIEW

**Comment by entrusc** [comment]
@ElectroBoy404NotFound can you please elaborate why you think this is an improvement to change the log level here to `INFO` when opening/closing the i2c bus?

**Comment by ElectroBoy404NotFound** [comment]
> @ElectroBoy404NotFound can you please elaborate why you think this is an improvement to change the log level here to `INFO` when opening/closing the i2c bus?

I just think that it makes more sense. If you want, you can only merge the README changes.

**Comment by ElectroBoy404NotFound** [comment]
I mean, its just an line to tell the user that we are opening/closing the i2c bus, so it made more sense for me.

**Comment by ElectroBoy404NotFound** [comment]
Also, nice project you have over here!

**Comment by entrusc** [comment]
> I mean, its just an line to tell the user that we are opening/closing the i2c bus, so it made more sense for me.

True, but some people prefer their log uncluttered with debug messages. But if you wanna see that message you can simply change the log level for the corresponding logger in your app to `DEBUG`.

**Comment by ElectroBoy404NotFound** [comment]
> > I mean, its just an line to tell the user that we are opening/closing the i2c bus, so it made more sense for me.
> 
> True, but some people prefer their log uncluttered with debug messages. But if you wanna see that message you can simply change the log level for the corresponding logger in your app to `DEBUG`.

Ahhh yes, i completly forgot about DEBUG.. Let me change that

**Comment by ElectroBoy404NotFound** [comment]
Also i'm updating it becuase i want my own copy even if you don't merge this pull.

**Comment by ElectroBoy404NotFound** [comment]
Should i close this pull?

**Comment by entrusc** [comment]
I incorporated your changes of the README.md to now not mention any specific IDE, but instead simply highlight how to build it using maven. I think every decent developer should be able to figure out how to open the project in their favorite IDE.

Thanks for your contribution :)

Closing this pull request now.

**Comment by ElectroBoy404NotFound** [comment]
@entrusc entrusc

**Comment by ElectroBoy404NotFound** [comment]
> I incorporated your changes of the README.md to now not mention any specific IDE, but instead simply highlight how to build 
it using maven. I think every decent developer should be able to figure out how to open the project in their favorite IDE.
> 
> Thanks for your contribution :)
> 
> Closing this pull request now.

Oh, thanks!

**Pull request closed without merging**
